services:
  - type: web
    name: ai-study-buddy
    env: python
    region: oregon  # or your preferred region
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False